### ISSUE TITLE
Redundant warning during similarity check with spacy

### ISSUE THREAD

**Issue by Mohaymin** [mirarifhasan/QASystem#4]
Spacy produces warning in the format: <File Url>: User Warning: [W008]: Evaluating Doc....

**Comment by Mohaymin** [comment]
Adding following two lines:
```
import warnings

warnings.filterwarnings("ignore", message=r"\[W008\]", category=UserWarning)
```
in constants.py after `import spacy` have solved this issue

**Comment by mirarifhasan** [comment]
Awesome!
